export default [
    {
        id: 1,
        social: "src/assets/icon-facebook.svg",
        follower: 87,
        describe: "Page Views",
        icon: true,
        follower_today: "3%",
    },
    {
        id: 2,
        social: "src/assets/icon-facebook.svg",
        follower: 52,
        describe: "Likes",
        icon: false,
        follower_today: "2%",
    },
    {
        id: 3,
        social: "src/assets/icon-instagram.svg",
        follower: 5462,
        describe: "Likes",
        icon: true,
        follower_today: "2257%",
    },
    {
        id: 4,
        social: "src/assets/icon-facebook.svg",
        follower: "52k",
        describe: "Profile Views",
        icon: true,
        follower_today: "1375%",
    },
    {
        id: 5,
        social: "src/assets/icon-facebook.svg",
        follower: 117,
        describe: "Retweets",
        icon: true,
        follower_today: "303%",
    },
    {
        id: 6,
        social: "src/assets/icon-twitter.svg",
        follower: 507,
        describe: "Likes",
        icon: true,
        follower_today: "553%",
    },
    {
        id: 7,
        social: "src/assets/icon-youtube.svg",
        follower: 107,
        describe: "Likes",
        icon: false,
        follower_today: "19%",
    },
    {
        id: 8,
        social: "src/assets/icon-youtube.svg",
        follower: 1407,
        describe: "Total Views",
        icon: false,
        follower_today: "12%",
    },
]